# Generated by Django 4.2.5 on 2023-09-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_pokemon_catch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='pokemons',
        ),
    ]
